# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0002_auto_20160808_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_number', models.IntegerField()),
                ('count_tenminutesinterval', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
