# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0003_visitor_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor_Time',
            new_name='VisitorTime',
        ),
    ]
