# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0004_auto_20160810_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitortime',
            old_name='count_tenminutesinterval',
            new_name='count_minutesinterval',
        ),
    ]
