# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0006_auto_20160810_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cakeflavor', models.CharField(max_length=20)),
                ('Buyumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nickname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('Cakeflavor', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
    ]
