# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0007_buy_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Cakeflavor',
            new_name='Flavor',
        ),
    ]
