# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0008_auto_20160818_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Timepost',
            field=models.CharField(default='', max_length=20),
        ),
    ]
