# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0011_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='Nickname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Flavor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
