# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0012_auto_20160818_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Timepost',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
