# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0014_remove_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Nickname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
