# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0015_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Customer_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='buy',
            name='Email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='buy',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='buy',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Cakeflavor',
            field=models.CharField(default='', max_length=20),
        ),
    ]
