# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0016_auto_20160819_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Timepost',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
