# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0017_buy_timepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
    ]
