# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0018_auto_20160819_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='Buyumber',
            new_name='Buynumber',
        ),
    ]
