# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0019_auto_20160820_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Buynumber',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Cakeflavor',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
