# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0020_auto_20160825_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='Cakeflavor',
        ),
        migrations.AddField(
            model_name='buy',
            name='Cakeflavor',
            field=models.ManyToManyField(to='cheesecake.Cake'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
