# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0021_auto_20160826_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Flavor',
            field=models.CharField(default='', max_length=200),
        ),
    ]
