# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0022_auto_20160829_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Flavor',
        ),
        migrations.AddField(
            model_name='comment',
            name='Flavor',
            field=models.ManyToManyField(to='cheesecake.Cake'),
        ),
    ]
