# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0024_buy_catchmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='Catchlocation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
