# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0025_buy_catchlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='Price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
