# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0026_cake_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
