# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0028_buy_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitortime',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visitortime',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
