# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0028_buy_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
