# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0030_totalviewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Totalviewer',
        ),
    ]
