# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0031_auto_20160927_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitortime',
            name='totalviewer',
        ),
    ]
