# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0031_delete_totalviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
