# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0032_remove_visitortime_totalviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalviewer', models.IntegerField(default=0)),
            ],
        ),
    ]
