# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0033_totalviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalviewer',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
