# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesecake', '0034_totalviewer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalviewer',
            name='totalviewer',
            field=models.IntegerField(),
        ),
    ]
